services:
  auth:
    image: auth-microservice
    ports:
      - '5000:5000'
  triage:
    image: triage-microservice
    ports:
      - '5001:5001'
  waitlist:
    image: waitlist-microservice
    ports:
      - '5002:5002'